#ifndef QTLIBS_H
#define QTLIBS_H
#include <QFrame>
#include <QWidget>
#include <QLabel>
#include <QApplication>
#include <QMenu>
#include <QCloseEvent>
#include <QAction>
#include <QPushButton>
#include <QPainter>
#include <QStringList>
#include <QMouseEvent>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QInputDialog>
#include <QRect>
#include <QMessageBox>
#include <QThread>
#include <QList>
#include <QColor>
#include <QColorDialog>
#include <QToolButton>
#include <QVector>
#include <QPolygon>
#include <QLine>
#include <cmath>
#include <iostream>
#endif //QTLIBS_H
